import { ColorModeSwitch, StrictColorModeSwitch } from '../types';
export declare type _EuiThemeButtonColors = {
    backgroundPrimary: ColorModeSwitch;
    backgroundAccent: ColorModeSwitch;
    backgroundAccentSecondary: ColorModeSwitch;
    backgroundSuccess: ColorModeSwitch;
    backgroundWarning: ColorModeSwitch;
    backgroundDanger: ColorModeSwitch;
    backgroundText: ColorModeSwitch;
    backgroundDisabled: ColorModeSwitch;
    backgroundFilledPrimary: ColorModeSwitch;
    backgroundFilledAccent: ColorModeSwitch;
    backgroundFilledAccentSecondary: ColorModeSwitch;
    backgroundFilledSuccess: ColorModeSwitch;
    backgroundFilledWarning: ColorModeSwitch;
    backgroundFilledDanger: ColorModeSwitch;
    backgroundFilledText: ColorModeSwitch;
    backgroundFilledDisabled: ColorModeSwitch;
    backgroundEmptyPrimaryHover: ColorModeSwitch;
    backgroundEmptyAccentHover: ColorModeSwitch;
    backgroundEmptyAccentSecondaryHover: ColorModeSwitch;
    backgroundEmptySuccessHover: ColorModeSwitch;
    backgroundEmptyWarningHover: ColorModeSwitch;
    backgroundEmptyDangerHover: ColorModeSwitch;
    backgroundEmptyTextHover: ColorModeSwitch;
    textColorPrimary: ColorModeSwitch;
    textColorAccent: ColorModeSwitch;
    textColorAccentSecondary: ColorModeSwitch;
    textColorSuccess: ColorModeSwitch;
    textColorWarning: ColorModeSwitch;
    textColorDanger: ColorModeSwitch;
    textColorText: ColorModeSwitch;
    textColorDisabled: ColorModeSwitch;
    textColorFilledPrimary: ColorModeSwitch;
    textColorFilledAccent: ColorModeSwitch;
    textColorFilledAccentSecondary: ColorModeSwitch;
    textColorFilledSuccess: ColorModeSwitch;
    textColorFilledWarning: ColorModeSwitch;
    textColorFilledDanger: ColorModeSwitch;
    textColorFilledText: ColorModeSwitch;
    textColorFilledDisabled: ColorModeSwitch;
};
export declare type _EuiThemeButton = StrictColorModeSwitch<_EuiThemeButtonColors> & {};
